// Auto-generated contract type bindings for ShadowPay.compact (Compact v0.23 / Minokawa)
// Generated by Midnight Compact Compiler

export interface ShadowPayCircuits {
  deposit_payroll_budget(admin: Uint8Array, budget: bigint, batchHash: Uint8Array): Promise<void>;
  commit_recipient_split(
    recipientCommitment: Uint8Array,
    minGuaranteedFloor: bigint,
    salaryAmount: bigint,
    recipientNullifier: Uint8Array
  ): Promise<void>;
  finalize_settlement_batch(): Promise<void>;
  claim_private_payout(
    recipientCommitment: Uint8Array,
    claimedAmount: bigint,
    submittedNullifier: Uint8Array
  ): Promise<void>;
}

export interface ShadowPayLedgerState {
  admin_pk: Uint8Array;
  total_funded_budget: bigint;
  total_allocated_amount: bigint;
  batch_hash: Uint8Array;
  recipient_count: number;
  claims_count: number;
  is_settled: boolean;
}

export const CONTRACT_NAME = 'ShadowPay';
export const CONTRACT_VERSION = '0.23.0';
