// Auto-generated contract type bindings for ShadowPay.compact (Compact v0.23 / Minokawa)
// Generated by Midnight Compact Compiler

export interface ShadowPayWitnesses {
  get_recipient_secret(): Uint8Array;
  get_salary_amount(): bigint;
  get_min_committed_amount(): bigint;
  get_batch_total_allocation(): bigint;
  compute_payout_nullifier(secret: Uint8Array, batchHash: Uint8Array): Uint8Array;
  verify_claim_witness(secret: Uint8Array, expectedCommitment: Uint8Array, claimedAmount: bigint): boolean;
  verify_auditor_key(key: Uint8Array, expectedHash: Uint8Array): boolean;
}

export interface ShadowPayCircuits {
  deposit_payroll_budget(
    admin: Uint8Array,
    budget: bigint,
    batchHash: Uint8Array,
    auditorHash: Uint8Array
  ): Promise<void>;

  commit_recipient_split(
    recipientCommitment: Uint8Array,
    minGuaranteedFloor: bigint
  ): Promise<void>;

  finalize_settlement_batch(): Promise<void>;

  claim_private_payout(
    recipientCommitment: Uint8Array,
    submittedNullifier: Uint8Array
  ): Promise<void>;

  disclose_payroll_audit(
    auditKey: Uint8Array
  ): Promise<[boolean, bigint, number]>;
}

export interface ShadowPayLedgerState {
  admin_pk: Uint8Array;
  total_funded_budget: bigint;
  batch_hash: Uint8Array;
  authorized_auditor_hash: Uint8Array;
  recipient_count: number;
  claims_count: number;
  is_settled: boolean;
  commitments: Map<string, boolean>;
  spent_nullifiers: Map<string, boolean>;
}

export const CONTRACT_NAME = 'ShadowPay';
export const CONTRACT_VERSION = '0.23.0';
